@extends('layouts.admin')
@section('title','New Purchase')
@section('content')
<div class="content-heading mb-4"><h1>New purchase</h1><p>Every purchase belongs to a Warehouse and Supplier, so inventory can be tracked per location.</p></div><form method="POST" action="{{ route('admin.purchases.store') }}">@csrf
<div class="panel mb-4"><div class="row g-3 align-items-end"><div class="col-md-8"><label class="form-label">Supplier</label><select name="supplier_id" class="form-select" required><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }} — {{ $supplier->phone }}</option>@endforeach</select></div><div class="col-md-4"><a href="{{ route('admin.suppliers.create') }}" class="btn border w-100"><i class="bi bi-person-plus me-1"></i>Add new supplier</a></div></div></div>
<div class="panel mb-4"><div class="panel-heading mb-3">Purchase details</div><div class="row g-3"><div class="col-md-4"><label class="form-label">Warehouse</label><select name="warehouse_id" class="form-select" required><option value="">Select warehouse</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }} — {{ $warehouse->code }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Supplier name</label><input name="supplier_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Supplier phone</label><input name="supplier_phone" class="form-control"></div><div class="col-md-4"><label class="form-label">Invoice / reference no.</label><input name="invoice_number" class="form-control"></div><div class="col-md-4"><label class="form-label">Purchase date</label><input name="purchase_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select"><option value="received">Received</option><option value="ordered">Ordered</option><option value="draft">Draft</option></select></div></div></div>
<div class="panel mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><div class="panel-heading">Purchased items</div><button type="button" class="btn btn-sm border" id="add-purchase-line">+ Add item</button></div><div class="table-responsive"><table class="table" id="purchase-lines"><thead><tr><th>Product</th><th style="width:130px">Quantity</th><th style="width:160px">Unit cost</th><th style="width:150px">Line total</th><th></th></tr></thead><tbody><tr><td><select name="items[0][product_id]" class="form-select product-select"><option value="">Custom item</option>@foreach($products as $product)<option value="{{ $product->id }}" data-name="{{ $product->name }}">{{ $product->name }}</option>@endforeach</select><input name="items[0][product_name]" class="form-control mt-2 product-name" placeholder="Product / item name" required></td><td><input name="items[0][quantity]" value="1" type="number" step=".001" min=".001" class="form-control line-qty" required></td><td><input name="items[0][unit_cost]" value="0" type="number" step=".01" min="0" class="form-control line-cost" required></td><td class="line-total">$0.00</td><td><button type="button" class="btn btn-sm text-danger remove-line">×</button></td></tr></tbody></table></div><div class="row justify-content-end g-3"><div class="col-md-3"><label class="form-label">Discount</label><input name="discount" value="0" type="number" step=".01" class="form-control purchase-adjustment"></div><div class="col-md-3"><label class="form-label">Tax</label><input name="tax" value="0" type="number" step=".01" class="form-control purchase-adjustment"></div><div class="col-md-3"><label class="form-label">Grand total</label><div class="form-control fw-bold" id="purchase-grand-total">$0.00</div></div></div></div>
<div class="panel mb-4"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="3" placeholder="Delivery condition, payment notes, or internal comments."></textarea></div><button class="btn text-white px-4" style="background:var(--brand)">Save purchase</button></form>
<template id="purchase-line-template"><tr><td><select class="form-select product-select"><option value="">Custom item</option>@foreach($products as $product)<option value="{{ $product->id }}" data-name="{{ $product->name }}">{{ $product->name }}</option>@endforeach</select><input class="form-control mt-2 product-name" placeholder="Product / item name" required></td><td><input value="1" type="number" step=".001" min=".001" class="form-control line-qty" required></td><td><input value="0" type="number" step=".01" min="0" class="form-control line-cost" required></td><td class="line-total">$0.00</td><td><button type="button" class="btn btn-sm text-danger remove-line">×</button></td></tr></template>
@endsection
