<?php $__env->startSection('title','Opening Balance '.$balance->year->name); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between align-items-center mb-4 no-print"><div class="content-heading"><h1>Opening Balance</h1><p><?php echo e($balance->year->name); ?></p></div><button type="button" class="btn text-white" style="background:var(--brand)" onclick="window.print()"><i class="bi bi-file-earmark-pdf me-1"></i>Export PDF</button></div>
<article class="panel invoice-sheet mx-auto">
    <header class="d-flex justify-content-between border-bottom pb-4 mb-4"><div><div class="brand-name fs-4">EBay</div><div class="text-muted small mt-2">Financial year opening balance</div></div><div class="text-end"><div class="fw-bold"><?php echo e($balance->year->name); ?></div><div class="small text-muted"><?php echo e($balance->balance_date->format('d M Y')); ?></div></div></header>
    <table class="table"><thead><tr><th>Code</th><th>Account head</th><th class="text-end">Debit</th><th class="text-end">Credit</th></tr></thead><tbody><?php $__currentLoopData = $balance->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($item->account?->code ?? 'Archived'); ?></td><td><?php echo e($item->account?->head_name ?? 'Archived account #'.$item->account_coa_id); ?></td><td class="text-end"><?php echo e($item->debit ? 'BDT '.number_format($item->debit,2) : '—'); ?></td><td class="text-end"><?php echo e($item->credit ? 'BDT '.number_format($item->credit,2) : '—'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody><tfoot><tr><th colspan="2" class="text-end">Total</th><th class="text-end">BDT <?php echo e(number_format($balance->items->sum('debit'),2)); ?></th><th class="text-end">BDT <?php echo e(number_format($balance->items->sum('credit'),2)); ?></th></tr></tfoot></table>
    <footer class="border-top pt-4 mt-5 row text-muted small"><div class="col-6">Prepared by: ____________________</div><div class="col-6 text-end">Approved by: ____________________</div></footer>
</article>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH F:\laragon\www\Ecommerce\resources\views\admin\accounts\opening-balance-print.blade.php ENDPATH**/ ?>