<?php $__env->startSection('title', ucfirst($voucherType).' Voucher '.$voucherNo); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between align-items-center mb-4 no-print">
    <div class="content-heading"><h1><?php echo e(ucfirst($voucherType)); ?> Voucher</h1><p><?php echo e($voucherNo); ?></p></div>
    <div class="d-flex gap-2"><button type="button" class="btn btn-outline-secondary" onclick="window.close()">Close</button><button type="button" class="btn text-white" style="background:var(--brand)" onclick="window.print()"><i class="bi bi-file-earmark-pdf me-1"></i>Export PDF</button></div>
</div>
<article class="panel invoice-sheet mx-auto voucher-sheet">
    <header class="d-flex justify-content-between border-bottom pb-4 mb-4"><div><div class="brand-name fs-4">EBay</div><div class="text-muted small mt-2">Accounting voucher</div></div><div class="text-end"><div class="small text-uppercase text-muted"><?php echo e(ucfirst($voucherType)); ?> voucher</div><div class="fw-bold fs-5"><?php echo e($voucherNo); ?></div><div class="text-muted small"><?php echo e($transactionDate->format('d M Y')); ?></div></div></header>
    <div class="row mb-4"><div class="col-sm-7"><div class="text-muted small text-uppercase mb-1">Narration</div><div><?php echo e($narration ?: 'System-generated accounting entry'); ?></div></div><div class="col-sm-5 text-sm-end mt-3 mt-sm-0"><div class="text-muted small text-uppercase mb-1">Reference</div><div><?php echo e($entries->first()->supplier?->name ?: ($entries->first()->customer?->full_name ?: 'Internal transaction')); ?></div></div></div>
    <table class="table"><thead><tr><th>Account code</th><th>Account head</th><th class="text-end">Debit</th><th class="text-end">Credit</th></tr></thead><tbody><?php $__currentLoopData = $entries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $entry): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($entry->account->code); ?></td><td><?php echo e($entry->account->head_name); ?></td><td class="text-end"><?php echo e($entry->entry_type === 'debit' ? 'BDT '.number_format($entry->amount,2) : '—'); ?></td><td class="text-end"><?php echo e($entry->entry_type === 'credit' ? 'BDT '.number_format($entry->amount,2) : '—'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody><tfoot><tr><th colspan="2" class="text-end">Total</th><th class="text-end">BDT <?php echo e(number_format($entries->where('entry_type','debit')->sum('amount'),2)); ?></th><th class="text-end">BDT <?php echo e(number_format($entries->where('entry_type','credit')->sum('amount'),2)); ?></th></tr></tfoot></table>
    <footer class="border-top pt-4 mt-5 row text-muted small"><div class="col-6">Prepared by: ____________________</div><div class="col-6 text-end">Approved by: ____________________</div></footer>
</article>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH F:\laragon\www\Ecommerce\resources\views/admin/accounts/voucher-print.blade.php ENDPATH**/ ?>