<?php $__env->startSection('title',$result['title']); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex flex-wrap align-items-start justify-content-between gap-3 content-heading mb-4">
    <div><div class="small text-uppercase fw-semibold" style="color:var(--brand)">Accounts · Reports</div><h1><?php echo e($result['title']); ?></h1><p>Live report generated from the current business and accounting records.</p></div>
    <div class="d-flex gap-2 no-print"><button type="button" class="btn btn-light border" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print</button><button type="button" class="btn text-white" style="background:var(--brand)" onclick="window.print()"><i class="bi bi-file-earmark-pdf me-1"></i>Export PDF</button></div>
</div>

<div class="panel mb-4 d-print-none">
    <div class="row g-3">
        <div class="col-lg-4"><label class="form-label">Report</label><select class="form-select" onchange="if(this.value) window.location=this.value"><optgroup label="Financial reports"><?php $__currentLoopData = $financialReports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e(route('admin.accounts.reports',$key)); ?>" <?php if($report===$key): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></optgroup><optgroup label="Business reports"><?php $__currentLoopData = $operationalReports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e(route('admin.accounts.reports',$key)); ?>" <?php if($report===$key): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></optgroup></select></div>
    </div>
    <form method="GET" action="<?php echo e(route('admin.accounts.reports',$report)); ?>" class="row g-3 mt-1">
        <?php if(in_array('date',$result['filterKeys'])): ?><div class="col-md-3"><label class="form-label">From date</label><input type="date" name="from_date" value="<?php echo e($filters['from_date']??''); ?>" class="form-control"></div><div class="col-md-3"><label class="form-label">To date</label><input type="date" name="to_date" value="<?php echo e($filters['to_date']??''); ?>" class="form-control"></div><?php endif; ?>
        <?php if(in_array('account',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">Account head</label><select name="account_id" class="form-select"><option value="">All account heads</option><?php $__currentLoopData = $accounts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $account): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($account->id); ?>" <?php if(($filters['account_id']??null)==$account->id): echo 'selected'; endif; ?>><?php echo e($account->code); ?> — <?php echo e($account->head_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('product',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">Product</label><select name="product_id" class="form-select"><option value="">All products</option><?php $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $product): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($product->id); ?>" <?php if(($filters['product_id']??null)==$product->id): echo 'selected'; endif; ?>><?php echo e($product->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('category',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">Category</label><select name="category_id" class="form-select"><option value="">All categories</option><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->id); ?>" <?php if(($filters['category_id']??null)==$category->id): echo 'selected'; endif; ?>><?php echo e($category->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('warehouse',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">Warehouse</label><select name="warehouse_id" class="form-select"><option value="">All warehouses</option><?php $__currentLoopData = $warehouses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $warehouse): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($warehouse->id); ?>" <?php if(($filters['warehouse_id']??null)==$warehouse->id): echo 'selected'; endif; ?>><?php echo e($warehouse->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('customer',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">Customer</label><select name="customer_id" class="form-select"><option value="">All customers</option><?php if($report!=='customer-ledger'): ?><option value="walking" <?php if(($filters['customer_id']??null)==='walking'): echo 'selected'; endif; ?>>Walking customer / guest</option><?php endif; ?> <?php $__currentLoopData = $customers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $customer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($customer->id); ?>" <?php if(($filters['customer_id']??null)==$customer->id): echo 'selected'; endif; ?>><?php echo e($customer->full_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('supplier',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">Supplier</label><select name="supplier_id" class="form-select"><option value="">All suppliers</option><?php $__currentLoopData = $suppliers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $supplier): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($supplier->id); ?>" <?php if(($filters['supplier_id']??null)==$supplier->id): echo 'selected'; endif; ?>><?php echo e($supplier->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('user',$result['filterKeys'])): ?><div class="col-md-4"><label class="form-label">User</label><select name="user_id" class="form-select"><option value="">All users</option><?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($user->id); ?>" <?php if(($filters['user_id']??null)==$user->id): echo 'selected'; endif; ?>><?php echo e($user->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(count($result['filterKeys'])): ?><div class="col-md-2 d-flex align-items-end"><button class="btn text-white w-100" style="background:var(--brand)"><i class="bi bi-funnel me-1"></i>Apply</button></div><div class="col-md-2 d-flex align-items-end"><a href="<?php echo e(route('admin.accounts.reports',$report)); ?>" class="btn btn-light border w-100">Reset</a></div><?php endif; ?>
    </form>
</div>

<?php if($result['notice']): ?><div class="alert alert-info border-0"><i class="bi bi-info-circle me-2"></i><?php echo e($result['notice']); ?></div><?php endif; ?>
<?php if($result['totals']): ?><div class="row g-3 mb-4"><?php $__currentLoopData = $result['totals']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-sm-6 col-xl-3"><div class="panel py-3 h-100"><div class="small text-muted text-uppercase fw-semibold"><?php echo e($label); ?></div><div class="fs-4 fw-bold mt-1"><?php echo e(in_array(strtolower($label),['orders','purchases','quantity','due orders']) ? number_format((float)$value, str_contains(strtolower($label),'quantity')?3:0) : '$'.number_format((float)$value,2)); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?>

<div class="panel p-0 overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><?php $__currentLoopData = $result['columns']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $column): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th><?php echo e($column); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $result['rows']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><?php $__currentLoopData = $row; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php echo e($value); ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="<?php echo e(max(count($result['columns']),1)); ?>" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No matching records found.</td></tr><?php endif; ?></tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH F:\laragon\www\Ecommerce\resources\views\admin\accounts\report.blade.php ENDPATH**/ ?>