<?php $__env->startSection('title', 'Media Library'); ?>
<?php $__env->startSection('content'); ?>
<div class="content-heading mb-4"><h1>Media library</h1><p>Upload images once and reuse them for category icons, banners, products, and storefront content.</p></div>
<div class="row g-4"><div class="col-lg-4"><div class="panel"><div class="panel-heading mb-3">Upload images</div><form action="<?php echo e(route('admin.media.store')); ?>" method="POST" enctype="multipart/form-data"><?php echo csrf_field(); ?><label for="images" class="border rounded-3 p-4 text-center w-100" style="border-style:dashed!important;border-color:var(--brand)!important;background:var(--brand-soft);cursor:pointer"><i class="bi bi-cloud-arrow-up fs-2 d-block mb-2" style="color:var(--brand)"></i><strong class="d-block small">Choose images to upload</strong><span class="small" style="color:var(--muted)">JPG, PNG, WebP or GIF · Max 4 MB each</span></label><input id="images" name="images[]" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple class="d-none" required><?php $__errorArgs = ['images'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?><div class="text-danger small mt-2"><?php echo e($message); ?></div><?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?><button class="btn text-white w-100 mt-3 py-2" style="background:var(--brand);border-radius:10px"><i class="bi bi-upload me-1"></i>Upload to library</button></form></div></div><div class="col-lg-8"><div class="panel"><div class="d-flex justify-content-between align-items-center mb-3"><div class="panel-heading">Gallery</div><span class="small" style="color:var(--muted)"><?php echo e($media->total()); ?> image<?php echo e($media->total() === 1 ? '' : 's'); ?></span></div><div class="row row-cols-2 row-cols-md-3 g-3"><?php $__empty_1 = true; $__currentLoopData = $media; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="col"><div class="image-tile"><img src="<?php echo e($item->url); ?>" alt="<?php echo e($item->original_name); ?>"><div class="p-2"><div class="small text-truncate fw-semibold"><?php echo e($item->original_name); ?></div><div class="small" style="color:var(--muted)"><?php echo e(number_format($item->size / 1024, 0)); ?> KB</div></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="col-12 text-center py-5" style="color:var(--muted)"><i class="bi bi-images fs-2 d-block mb-2"></i>Your gallery is empty. Upload an image to get started.</div><?php endif; ?></div><?php if($media->hasPages()): ?><div class="mt-3"><?php echo e($media->links()); ?></div><?php endif; ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH F:\laragon\www\Ecommerce\resources\views\admin\media\index.blade.php ENDPATH**/ ?>