<?php $__env->startSection('title', $draft ? 'Continue POS Draft' : 'Point of Sale'); ?>
<?php $__env->startSection('content'); ?>
<?php ($selectedWarehouseId = $draft ? $draft->warehouse_id : null); ?>
<div class="content-heading mb-4">
    <h1><?php echo e($draft ? 'Continue POS Draft' : 'Point of Sale'); ?></h1>
    <p><?php echo e($draft ? 'Your saved cart has been restored. Review it and complete the sale.' : 'Select a warehouse first. Stock shown belongs to that location.'); ?></p>
</div>
<div class="row g-4">
    <div class="col-xl-8"><div class="panel">
        <div class="row g-2 mb-4">
            <div class="col-md-4"><label class="form-label">Selling warehouse <span class="text-danger">*</span></label><select class="form-select" id="pos-warehouse"><option value="">Select warehouse</option><?php $__currentLoopData = $warehouses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $warehouse): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($warehouse->id); ?>" <?php echo e($selectedWarehouseId == $warehouse->id ? 'selected' : ''); ?>><?php echo e($warehouse->name); ?> — <?php echo e($warehouse->code); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div class="col-md-3"><label class="form-label">Brand</label><select class="form-select" id="pos-brand"><option value="">All brands</option><?php $__currentLoopData = $brands; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $brand): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($brand->id); ?>"><?php echo e($brand->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div class="col-md-5"><label class="form-label">Find product</label><div class="input-group"><input id="pos-search" class="form-control" placeholder="Search by product name or SKU"><span class="input-group-text"><i class="bi bi-search"></i></span></div></div>
        </div>
        <div class="alert alert-primary border-0 small py-2" id="pos-warehouse-notice"><i class="bi bi-info-circle me-1"></i>Choose a warehouse to see available inventory.</div>
        <div class="row g-3" id="pos-products">
            <?php $__empty_1 = true; $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $product): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <div class="col-md-6 pos-product" data-name="<?php echo e(strtolower($product->name.' '.$product->sku)); ?>" data-brand="<?php echo e($product->brand_id); ?>" data-stocks='<?php echo e($product->warehouseStocks->pluck('quantity','warehouse_id')->toJson()); ?>'>
                <button type="button" class="w-100 text-start border rounded-3 p-3 bg-white pos-add" disabled data-id="<?php echo e($product->id); ?>" data-name="<?php echo e($product->name); ?>" data-price="<?php echo e($product->selling_price); ?>"><div class="d-flex align-items-center gap-3"><div class="pos-product-image"><?php if($product->thumbnail): ?><img src="<?php echo e($product->thumbnail->url); ?>" alt="<?php echo e($product->name); ?>"><?php else: ?><i class="bi bi-image"></i><?php endif; ?></div><div class="flex-grow-1"><div class="fw-semibold"><?php echo e($product->name); ?></div><div class="small text-muted"><?php echo e($product->sku); ?></div><div class="small mt-1 pos-stock text-muted">Select warehouse</div></div><div class="text-end"><div class="fw-bold" style="color:var(--brand)">$<?php echo e(number_format($product->selling_price,2)); ?></div><div class="small text-muted">Click to add</div></div></div></button>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="col-12 text-center py-5 text-muted">Add products first, then they will appear here for POS sales.</div><?php endif; ?>
        </div>
    </div></div>
    <div class="col-xl-4"><div class="panel h-100">
        <div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3"><div class="panel-heading"><?php echo e($draft ? $draft->order_number : 'Current sale'); ?></div><button id="pos-clear" type="button" class="btn btn-sm text-danger">Clear cart</button></div>
        <div id="pos-cart" class="vstack gap-3"><div class="text-center py-5 text-muted"><i class="bi bi-basket fs-2 d-block mb-2"></i>Cart is empty</div></div>
        <div class="border-top mt-3 pt-3"><div class="row g-2 mb-3"><div class="col-12"><label class="form-label">Customer</label><select id="pos-customer-id" class="form-select"><option value="">Walk-in Customer</option><?php $__currentLoopData = $customers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $customer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($customer->id); ?>" data-name="<?php echo e($customer->full_name); ?>" data-phone="<?php echo e($customer->phone); ?>" <?php if($draft?->customer_id===$customer->id): echo 'selected'; endif; ?>><?php echo e($customer->full_name); ?><?php echo e($customer->phone ? ' — '.$customer->phone : ''); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><div class="form-text">Choose Walk-in Customer for an anonymous cash sale, or select a registered customer for a due sale.</div></div><div id="pos-walk-in-fields" class="col-12"><div class="row g-2"><div class="col-12"><input id="pos-customer-name" class="form-control" value="<?php echo e($draft ? $draft->customer_name : ''); ?>" placeholder="Walk-in customer name (optional)"></div><div class="col-12"><input id="pos-customer-phone" class="form-control" value="<?php echo e($draft ? $draft->customer_phone : ''); ?>" placeholder="Walk-in customer phone (optional)"></div></div></div><div class="col-12"><label class="form-label">Payment method</label><select id="pos-payment-method" class="form-select"><?php $__currentLoopData = $paymentMethods; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $method): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($method->id); ?>" <?php if($draft?->payment_method_id===$method->id): echo 'selected'; endif; ?>><?php echo e($method->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><option value="due" <?php if($draft?->payment_method==='Due'): echo 'selected'; endif; ?>>Due — Customer Receivable</option></select></div></div><div class="d-flex justify-content-between mb-2"><span>Subtotal</span><strong id="pos-subtotal">$0.00</strong></div><div class="d-flex justify-content-between fs-5"><strong>Total</strong><strong id="pos-total" style="color:var(--brand)">$0.00</strong></div><div class="d-grid gap-2 mt-3"><button class="btn btn-outline-primary" id="pos-save-draft" type="button"><i class="bi bi-pause-circle me-1"></i><?php echo e($draft ? 'Update draft' : 'Hold as draft'); ?></button><button class="btn text-white" id="pos-checkout" type="button" style="background:var(--brand)"><i class="bi bi-credit-card me-1"></i>Complete sale</button></div></div>
    </div></div>
</div>
<form id="pos-order-form" method="POST" action="<?php echo e($draft ? route('admin.pos.drafts.update',$draft) : route('admin.pos.orders.save')); ?>" class="d-none"><?php echo csrf_field(); ?> <?php if($draft): ?> <?php echo method_field('PUT'); ?> <?php endif; ?></form>
<?php if($draft): ?><div id="pos-draft-data" data-payment="<?php echo e($draft->payment_method_id ?: ($draft->payment_method === 'Due' ? 'due' : '')); ?>" data-items='<?php echo e($draft->items->map(function($item) { return ['product_id'=>$item->product_id,'product_name'=>$item->product_name,'quantity'=>(float)$item->quantity,'unit_price'=>(float)$item->unit_price]; })->toJson()); ?>'></div><?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH F:\laragon\www\Ecommerce\resources\views/admin/pos/index.blade.php ENDPATH**/ ?>