@extends('layouts.admin')
@php($editing = $product->exists)
@section('title',$editing ? 'Edit Product' : 'Add Product')
@section('content')
<div class="content-heading mb-4"><h1>{{ $editing ? 'Edit product' : 'Add new product' }}</h1><p>English product information, variants, prices, media, and SEO.</p></div><form method="POST" action="{{ $editing ? route('admin.products.update',$product) : route('admin.products.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="panel mb-4"><div class="panel-heading mb-3">Product information</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Product name</label><input name="name" value="{{ old('name',$product->name) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Product SKU</label><input name="sku" value="{{ old('sku',$product->sku) }}" class="form-control" placeholder="e.g. PRD-1001" required></div><div class="col-12"><label class="form-label">Short description</label><textarea name="short_description" class="form-control" rows="2" required>{{ old('short_description',$product->short_description) }}</textarea></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="5">{{ old('description',$product->description) }}</textarea></div></div></div>
<div class="panel mb-4"><div class="panel-heading mb-3">General information</div><div class="row g-3"><div class="col-md-4"><label class="form-label">Category</label><select name="category_id" class="form-select"><option value="">Select category</option>@foreach($categories as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Subcategories</label><select name="subcategory_ids[]" class="js-category-select" multiple>@foreach($subcategories as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Brand</label><select name="brand_id" class="form-select"><option value="">Select brand</option>@foreach($brands as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Color</label><select name="color_id" class="form-select"><option value="">Select color</option>@foreach($colors as $item)<option value="{{ $item->id }}">{{ $item->name }} ({{ $item->hex_code }})</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Unit</label><select name="unit_id" class="form-select"><option value="">Select unit</option>@foreach($units as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Size</label><select name="size_id" class="form-select"><option value="">Select size</option>@foreach($sizes as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Weight (kg)</label><input name="weight" type="number" step=".001" class="form-control"></div></div></div>
<div class="panel mb-4"><div class="panel-heading mb-3">Price & stock</div><div class="row g-3"><div class="col-md-3"><label class="form-label">Buying price</label><input name="buying_price" type="number" step=".01" class="form-control" required></div><div class="col-md-3"><label class="form-label">Selling price</label><input name="selling_price" type="number" step=".01" class="form-control" required></div><div class="col-md-2"><label class="form-label">Discount type</label><select name="discount_type" class="form-select"><option value="percent">Percent</option><option value="amount">Amount</option></select></div><div class="col-md-2"><label class="form-label">Discount</label><input name="discount" value="0" type="number" step=".01" class="form-control"></div><div class="col-md-2"><label class="form-label">Stock quantity</label><input name="stock_quantity" value="0" type="number" class="form-control" required></div></div></div>
<div class="panel mb-4"><div class="panel-heading mb-3">Images & SEO</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Thumbnail</label><input id="product-thumbnail-media" name="thumbnail_media_id" type="hidden"><div class="media-preview mb-2" data-media-preview="product-thumbnail-media"><span>No thumbnail selected</span></div><button type="button" class="btn border w-100" data-media-picker-target="product-thumbnail-media">Choose thumbnail</button></div><div class="col-md-6"><label class="form-label">Product video URL (optional)</label><input name="video_url" type="url" class="form-control" placeholder="https://..."></div><div class="col-12"><label class="form-label">Meta title</label><input name="meta_title" class="form-control"></div><div class="col-12"><label class="form-label">Meta description</label><textarea name="meta_description" class="form-control" rows="2"></textarea></div><div class="col-12"><label class="form-label">Meta keywords</label><input name="meta_keywords" class="form-control" placeholder="keyword, keyword"></div></div></div><button class="btn text-white px-4" style="background:var(--brand)">Save product</button></form>
@endsection
