<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title', 'Admin') · VeloraCommerce</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body><div class="admin-shell d-lg-flex"><aside class="sidebar d-flex flex-column"><div class="d-flex align-items-center gap-2 px-4 py-4"><div class="brand-mark"><i class="bi bi-bag-heart-fill"></i></div><div class="brand-name">Velora<span>Commerce</span></div></div><nav class="flex-grow-1 overflow-auto pb-4"><p class="nav-label">Workspace</p><a href="{{ route('admin.dashboard') }}" class="side-link"><i class="bi bi-grid-1x2-fill"></i> Dashboard</a><a href="#" class="side-link"><i class="bi bi-receipt"></i> Orders</a><p class="nav-label">Catalogue</p>
@php($categoryOpen = request()->routeIs('admin.categories.*') || request()->routeIs('admin.subcategories.*'))
<button class="side-link border-0 w-100 text-start {{ $categoryOpen ? 'active' : '' }}" type="button" data-bs-toggle="collapse" data-bs-target="#category-menu"><i class="bi bi-grid-3x3-gap-fill"></i> Category <i class="bi bi-chevron-down"></i></button><div id="category-menu" class="collapse {{ $categoryOpen ? 'show' : '' }}"><div class="ms-4 border-start"><a href="{{ route('admin.categories.index') }}" class="side-link py-2">All category</a><a href="{{ route('admin.categories.create') }}" class="side-link py-2">Add category</a><a href="{{ route('admin.subcategories.index') }}" class="side-link py-2">All subcategory</a><a href="{{ route('admin.subcategories.create') }}" class="side-link py-2">Add subcategory</a></div></div>
@php($variantOpen = request()->routeIs('admin.brands.*') || request()->routeIs('admin.colors.*') || request()->routeIs('admin.sizes.*') || request()->routeIs('admin.units.*'))
<button class="side-link border-0 w-100 text-start {{ $variantOpen ? 'active' : '' }}" type="button" data-bs-toggle="collapse" data-bs-target="#variant-menu"><i class="bi bi-boxes"></i> Product Variant <i class="bi bi-chevron-down"></i></button><div id="variant-menu" class="collapse {{ $variantOpen ? 'show' : '' }}"><div class="ms-4 border-start"><a href="{{ route('admin.brands.index') }}" class="side-link py-2">Brand</a><a href="{{ route('admin.colors.index') }}" class="side-link py-2">Color</a><a href="{{ route('admin.sizes.index') }}" class="side-link py-2">Size</a><a href="{{ route('admin.units.index') }}" class="side-link py-2">Unit</a></div></div><a href="{{ route('admin.media.index') }}" class="side-link"><i class="bi bi-images"></i> Media library</a></nav></aside>
<main class="flex-grow-1 min-vw-0"><header class="topbar px-3 px-lg-4 d-flex align-items-center"><button class="icon-button me-3" data-sidebar-toggle><i class="bi bi-list fs-4"></i></button><div><div class="topbar-title">Catalogue management</div><div class="topbar-subtitle">Organize your store for effortless discovery.</div></div></header><div class="page-content">@if(session('success'))<div class="alert alert-success border-0 rounded-3 mb-4">{{ session('success') }}</div>@endif @yield('content')</div></main></div>
<div class="modal fade" id="media-picker-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Choose from Media Library</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div id="media-picker-content" class="modal-body"></div></div></div></div></body></html>
