@extends('layouts.admin')
@section('title',$result['title'])
@section('content')
<div class="d-flex flex-wrap align-items-start justify-content-between gap-3 content-heading mb-4">
    <div><div class="small text-uppercase fw-semibold" style="color:var(--brand)">Accounts · Reports</div><h1>{{ $result['title'] }}</h1><p>Live report generated from the current business and accounting records.</p></div>
    <div class="d-flex gap-2 no-print"><button type="button" class="btn btn-light border" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print</button><button type="button" class="btn text-white" style="background:var(--brand)" onclick="window.print()"><i class="bi bi-file-earmark-pdf me-1"></i>Export PDF</button></div>
</div>

<div class="panel mb-4 d-print-none">
    <div class="row g-3">
        <div class="col-lg-4"><label class="form-label">Report</label><select class="form-select" onchange="if(this.value) window.location=this.value"><optgroup label="Financial reports">@foreach($financialReports as $key=>$label)<option value="{{ route('admin.accounts.reports',$key) }}" @selected($report===$key)>{{ $label }}</option>@endforeach</optgroup><optgroup label="Business reports">@foreach($operationalReports as $key=>$label)<option value="{{ route('admin.accounts.reports',$key) }}" @selected($report===$key)>{{ $label }}</option>@endforeach</optgroup></select></div>
    </div>
    <form method="GET" action="{{ route('admin.accounts.reports',$report) }}" class="row g-3 mt-1">
        @if(in_array('date',$result['filterKeys']))<div class="col-md-3"><label class="form-label">From date</label><input type="date" name="from_date" value="{{ $filters['from_date']??'' }}" class="form-control"></div><div class="col-md-3"><label class="form-label">To date</label><input type="date" name="to_date" value="{{ $filters['to_date']??'' }}" class="form-control"></div>@endif
        @if(in_array('account',$result['filterKeys']))<div class="col-md-4"><label class="form-label">Account head</label><select name="account_id" class="form-select"><option value="">All account heads</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($filters['account_id']??null)==$account->id)>{{ $account->code }} — {{ $account->head_name }}</option>@endforeach</select></div>@endif
        @if(in_array('product',$result['filterKeys']))<div class="col-md-4"><label class="form-label">Product</label><select name="product_id" class="form-select"><option value="">All products</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(($filters['product_id']??null)==$product->id)>{{ $product->name }}</option>@endforeach</select></div>@endif
        @if(in_array('category',$result['filterKeys']))<div class="col-md-4"><label class="form-label">Category</label><select name="category_id" class="form-select"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id']??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>@endif
        @if(in_array('warehouse',$result['filterKeys']))<div class="col-md-4"><label class="form-label">Warehouse</label><select name="warehouse_id" class="form-select"><option value="">All warehouses</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(($filters['warehouse_id']??null)==$warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></div>@endif
        @if(in_array('customer',$result['filterKeys']))<div class="col-md-4"><label class="form-label">Customer</label><select name="customer_id" class="form-select"><option value="">All customers</option>@if($report!=='customer-ledger')<option value="walking" @selected(($filters['customer_id']??null)==='walking')>Walking customer / guest</option>@endif @foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(($filters['customer_id']??null)==$customer->id)>{{ $customer->full_name }}</option>@endforeach</select></div>@endif
        @if(in_array('supplier',$result['filterKeys']))<div class="col-md-4"><label class="form-label">Supplier</label><select name="supplier_id" class="form-select"><option value="">All suppliers</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(($filters['supplier_id']??null)==$supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div>@endif
        @if(in_array('user',$result['filterKeys']))<div class="col-md-4"><label class="form-label">User</label><select name="user_id" class="form-select"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['user_id']??null)==$user->id)>{{ $user->name }}</option>@endforeach</select></div>@endif
        @if(count($result['filterKeys']))<div class="col-md-2 d-flex align-items-end"><button class="btn text-white w-100" style="background:var(--brand)"><i class="bi bi-funnel me-1"></i>Apply</button></div><div class="col-md-2 d-flex align-items-end"><a href="{{ route('admin.accounts.reports',$report) }}" class="btn btn-light border w-100">Reset</a></div>@endif
    </form>
</div>

@if($result['notice'])<div class="alert alert-info border-0"><i class="bi bi-info-circle me-2"></i>{{ $result['notice'] }}</div>@endif
@if($result['totals'])<div class="row g-3 mb-4">@foreach($result['totals'] as $label=>$value)<div class="col-sm-6 col-xl-3"><div class="panel py-3 h-100"><div class="small text-muted text-uppercase fw-semibold">{{ $label }}</div><div class="fs-4 fw-bold mt-1">{{ in_array(strtolower($label),['orders','purchases','quantity','due orders']) ? number_format((float)$value, str_contains(strtolower($label),'quantity')?3:0) : '$'.number_format((float)$value,2) }}</div></div></div>@endforeach</div>@endif

<div class="panel p-0 overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr>@foreach($result['columns'] as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>@forelse($result['rows'] as $row)<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach</tr>@empty<tr><td colspan="{{ max(count($result['columns']),1) }}" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No matching records found.</td></tr>@endforelse</tbody></table></div></div>
@endsection
