<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PosOrder;
use App\Models\Product;
use App\Models\WarehouseProductStock;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class PosOrderController extends Controller
{
    public function history(): View { $query=PosOrder::with(['warehouse','items'])->where('status','completed');if(!auth()->user()->isSuperAdmin())$query->where('warehouse_id',auth()->user()->warehouse_id);return view('admin.pos.history',['orders'=>$query->latest()->paginate(15)]); }
    public function drafts(): View { $query=PosOrder::with(['warehouse','items'])->where('status','draft');if(!auth()->user()->isSuperAdmin())$query->where('warehouse_id',auth()->user()->warehouse_id);return view('admin.pos.drafts',['orders'=>$query->latest()->paginate(15)]); }
    public function save(Request $request): RedirectResponse { $data=$request->validate(['warehouse_id'=>'required|exists:warehouses,id','customer_name'=>'nullable|max:150','customer_phone'=>'nullable|max:30','payment_method'=>'nullable|max:30','status'=>'required|in:draft,completed','items'=>'required|array|min:1','items.*.product_id'=>'required|exists:products,id','items.*.product_name'=>'required|max:180','items.*.quantity'=>'required|numeric|gt:0','items.*.unit_price'=>'required|numeric|min:0']);if(!auth()->user()->isSuperAdmin())$data['warehouse_id']=auth()->user()->warehouse_id; return DB::transaction(function() use($data){if($data['status']==='completed') $this->reserveStock($data['warehouse_id'],$data['items']);$total=collect($data['items'])->sum(fn($item)=>$item['quantity']*$item['unit_price']);$order=PosOrder::create(['order_number'=>'POS-'.now()->format('ymdHis').'-'.random_int(100,999),'warehouse_id'=>$data['warehouse_id'],'customer_name'=>$data['customer_name']??null,'customer_phone'=>$data['customer_phone']??null,'payment_method'=>$data['payment_method']??null,'status'=>$data['status'],'subtotal'=>$total,'total'=>$total]);foreach($data['items'] as $item){$order->items()->create($item+['line_total'=>$item['quantity']*$item['unit_price']]);}return $data['status']==='draft'?to_route('admin.pos.drafts')->with('success','POS draft saved.'):to_route('admin.pos.invoice',$order)->with('success','Sale completed.');}); }
    public function invoice(PosOrder $order): View { abort_unless($order->status==='completed' && $this->canAccess($order),404); return view('admin.pos.invoice',['order'=>$order->load(['items','warehouse'])]); }
    public function continue(PosOrder $order): RedirectResponse { abort_unless($order->status==='draft' && $this->canAccess($order),404); return to_route('admin.pos.index',['draft'=>$order->id]); }
    public function update(Request $request, PosOrder $order): RedirectResponse { abort_unless($order->status==='draft' && $this->canAccess($order),404); $data=$request->validate(['warehouse_id'=>'required|exists:warehouses,id','customer_name'=>'nullable|max:150','customer_phone'=>'nullable|max:30','payment_method'=>'nullable|max:30','status'=>'required|in:draft,completed','items'=>'required|array|min:1','items.*.product_id'=>'required|exists:products,id','items.*.product_name'=>'required|max:180','items.*.quantity'=>'required|numeric|gt:0','items.*.unit_price'=>'required|numeric|min:0']);if(!auth()->user()->isSuperAdmin())$data['warehouse_id']=auth()->user()->warehouse_id; return DB::transaction(function() use($data,$order){if($data['status']==='completed') $this->reserveStock($data['warehouse_id'],$data['items']);$total=collect($data['items'])->sum(fn($item)=>$item['quantity']*$item['unit_price']);$order->update(['warehouse_id'=>$data['warehouse_id'],'customer_name'=>$data['customer_name']??null,'customer_phone'=>$data['customer_phone']??null,'payment_method'=>$data['payment_method']??null,'status'=>$data['status'],'subtotal'=>$total,'total'=>$total]);$order->items()->delete();foreach($data['items'] as $item){$order->items()->create($item+['line_total'=>$item['quantity']*$item['unit_price']]);}return $data['status']==='draft'?to_route('admin.pos.drafts')->with('success','POS draft updated.'):to_route('admin.pos.invoice',$order)->with('success','Sale completed.');}); }
    private function reserveStock(int $warehouseId, array $items): void { foreach($items as $item){$stock=WarehouseProductStock::where(['warehouse_id'=>$warehouseId,'product_id'=>$item['product_id']])->lockForUpdate()->first();if(!$stock || $stock->quantity < $item['quantity']) abort(422,'Insufficient stock for '.$item['product_name'].' in the selected warehouse.');$stock->decrement('quantity',$item['quantity']);Product::whereKey($item['product_id'])->where('stock_quantity','>=',$item['quantity'])->decrement('stock_quantity',$item['quantity']);} }
    private function canAccess(PosOrder $order): bool { return auth()->user()->isSuperAdmin() || $order->warehouse_id===auth()->user()->warehouse_id; }
}
